version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DusanRoot2001
      MYSQL_DATABASE: vyking
      MYSQL_USER: Dusan2001
      MYSQL_PASSWORD: 2001Dusan!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
